version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
            - echo "installing 1"
            - echo "added this line after creating a stack in NV region 'dev1-5-github-codebuild-project'"
            - echo "added this line after creating a stack in NV region 'dev1-7-github-codebuild-project'"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "this is build section inside buildspec.yml file"
            - echo "we will run some tests"
            - grep -Fq "AWS-CICD" index.html
    post_build:
        commands:
            - echo "we are in the post build phase"
            
