version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo $CODEBUILD_SOURCE_REPO_URL
            - |
                REPOSITORY=$(echo "$CODEBUILD_SOURCE_REPO_URL" | cut -d '/' -f 5 | cut -d '.' -f 1)
                Owner=$(echo "$CODEBUILD_SOURCE_REPO_URL" | cut -d '/' -f 4)
            - echo "REPOSITORY the AWS resources for $REPOSITORY"
            - echo "Owner the AWS resources for $Owner"
            - echo "installing something"
            - echo "installing 1"
            - echo "added this line after creating a stack in NV region 'dev1-5-github-codebuild-project'"
            - echo "added this line after creating a stack in NV region 'dev1-7-github-codebuild-project'"
            - echo "added line after creating a stack in NV region testing 3rd line 'dev1-7-github-codebuild-project'"
            - echo "added line after creating a stack in NV region testing 3rd line 'dev1-8-github-codebuild-project'"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "this is build section inside buildspec.yml file"
            - echo "we will run some tests"
            - grep -Fq "AWS-CICD" index.html
    post_build:
        commands:
            - echo "we are in the post build phase"
            
